# Lists vs Arrays

In [0]:
import numpy as np

In [0]:
L = [1,2,3]
A = np.array([1,2,3])

In [3]:
for e in L:
  print(e)

1
2
3


In [4]:
for f in A:
  print(f)

1
2
3


In [5]:
L.append(4)
L

[1, 2, 3, 4]

In [7]:
A.append(4)

AttributeError: ignored

In [8]:
L = L + [5]
L

[1, 2, 3, 4, 5]

In [0]:
L2 = []
for e in L:
  L2.append(e+e)
L2

In [10]:
A+A

array([2, 4, 6])

In [0]:
2*A

In [12]:
2*L

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5]

In [13]:
L**2

TypeError: ignored

In [14]:
L2 = []
for e in L:
  L2.append(e**2)
L2

[1, 4, 9, 16, 25]

In [15]:
A**2

array([1, 4, 9])

#  Dot product 1: For loop vs. cosine method vs. dot function

In [0]:
a = np.array([1,2])
b = np.array([2,1])

In [0]:
# Manually calculate dot product
dot = 0
for e,f in zip(a,b):
  dot +=e*f
dot

In [0]:
(a*b).sum()

In [0]:
np.sum(a*b)

In [0]:
np.dot(a,b)

In [0]:
a.dot(b)

In [0]:
b.dot(a)

In [0]:
# vector length
amag = np.sqrt((a*a).sum())
amag

In [0]:
amag = np.linalg.norm(a)
amag

In [0]:
cosangle = a.dot(b) / (np.linalg.norm(a) * np.linalg.norm(b))
cosangle

In [0]:
angle = np.arccos(cosangle)
angle

# Dot product 2: Speed comparison

In [0]:
# HOW FASTER IS VECTOR DOT PRODUCT NUMPY METHOD THAN MANUAL CALC USING FOR LOOPS???
from __future__ import print_function, division
from builtins import range
# Note: you may need to update your version of future
# sudo pip install -U future


import numpy as np
from datetime import datetime

a = np.random.randn(100)
b = np.random.randn(100)
T = 100000

def slow_dot_product(a, b):
  result = 0
  for e, f in zip(a, b):
    result += e*f
  return result

t0 = datetime.now()
for t in range(T):
  slow_dot_product(a, b)
dt1 = datetime.now() - t0

t0 = datetime.now()
for t in range(T):
  a.dot(b)
dt2 = datetime.now() - t0

print("dt1 / dt2:", dt1.total_seconds() / dt2.total_seconds())

#  Vectors and Matrices

In [0]:
M = np.array([[1,2],[3,4]])

In [0]:
L = [[1,2],[3,4]]

In [0]:
L[0]

In [0]:
L[0][0]

In [0]:
M[0][0]

In [0]:
M[0,0]

In [0]:
L[0,0]

In [0]:
# transpose
M.T

# Generating Matrices to Work With

In [0]:
Z = np.zeros(10)
Z

In [0]:
O = np.ones((5,5))
O

In [0]:
R = np.random.random((5,5))
R

In [17]:
G = np.random.randn(10,10)
G

array([[ 0.17382048,  2.26131975, -0.17290117, -1.1430106 ,  1.05035271,
         1.19220908,  1.5362553 , -1.07704362, -0.40571777,  2.02376039],
       [-1.29383323, -0.54567179, -0.8565554 , -2.79818221,  1.60934224,
         1.49402542,  0.79429409,  0.29207227, -0.10741214, -1.73157299],
       [ 0.09036207, -0.13936219, -0.35738126,  0.35010949,  1.53987961,
         0.06507513, -0.93146336, -1.73402029,  0.45140508, -0.23117923],
       [-0.6650489 , -1.12322864,  1.01793923, -0.587357  , -0.5350772 ,
         1.98779588,  0.14055031,  2.84814142,  0.61763511, -1.68908042],
       [ 1.30518295, -0.76082959, -1.49160356,  1.94605754, -0.69582736,
        -1.66192293,  0.21051904, -1.20502985, -1.19234369, -1.2021211 ],
       [-1.09653193, -0.13141339, -1.32899629,  0.67117331, -0.02855724,
        -0.08605577,  0.45395396, -0.08596376, -0.72648338,  1.44245831],
       [ 0.13126225, -0.73698872,  2.07083616, -1.04924943, -1.01335474,
        -1.34036175,  0.31685025,  0.1159803 

# Matrix Products

In [18]:
A = np.array([[1,2],[3,4],[5,6]])
B = np.array([[1,2,3],[4,5,6]])
C = A.dot(B)
C

array([[ 9, 12, 15],
       [19, 26, 33],
       [29, 40, 51]])

# More Matrix Operations

In [20]:
# inverse matrix
A = np.array([[1,2],[3,4]])
Ainv = np.linalg.inv(A)
Ainv


array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [21]:
Ainv.dot(A)

array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [22]:
# Matrix determinant (orizousa)
np.linalg.det(A)

-2.0000000000000004

In [23]:
# matrix diagonal
np.diag(A)

array([1, 4])

In [25]:
# outer product
a = np.array([1,2])
b = np.array([3,4])
np.outer(a,b)

array([[3, 4],
       [6, 8]])

In [26]:
# inner is same as dot product
np.inner(a,b)

11

In [27]:
a.dot(b)

11

In [28]:
# matrix trace (sum of the diagonal)


5

In [30]:
# calculate covariance of a matrix
X = np.random.randn(100,3)
cov = np.cov(X.T)
cov

array([[ 1.13746688, -0.12478421, -0.07145876],
       [-0.12478421,  1.08362371,  0.09377386],
       [-0.07145876,  0.09377386,  0.93778843]])

In [31]:
# eigen values
np.linalg.eig(cov)

(array([1.27714423, 0.99036525, 0.89136953]),
 array([[ 0.71702548, -0.69458793,  0.05849839],
        [-0.61829918, -0.6725258 , -0.40671264],
        [-0.32183937, -0.25545382,  0.91168129]]))

# Solving a Linear System

In [34]:
A = np.array([[1, 2],[3, 4]])
b = np.array([1,2])
x = np.linalg.inv(A).dot(b)
x

array([0. , 0.5])

In [36]:
x = np.linalg.solve(A,b)
x

array([0. , 0.5])

# Word Problem

In [39]:
# proplem. fee for children $1.5, for adults $4. 
# 2200 people at the fair, 
# $5050 collected. 
# how many children how many adults?
A = np.array([[1,1],[1.5,4]])
b = np.array([2200,5050])
x = np.linalg.solve(A,b)
x


array([1500.,  700.])